name: Build

on:
  workflow_dispatch:
  push:
    branches: 'main'
    paths:
      - 'palette/**'
      - 'processing/**'
      - 'pom.xml'
  pull_request:
    paths:
      - 'palette/**'
      - 'processing/**'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '8'
          cache: 'maven'

      - name: Build
        run: mvn -B -DskipTests clean package

      - name: Test
        run: mvn test

      - name: Archive Palette Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: palette-jars
          path: ./palette/target/*.jar

      - name: Archive Processing Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: processing-jars
          path: ./processing/target/*.jar
